import { Composer } from "telegraf";
import { MyContext } from "../../../bot";
import { Wallet } from "../../../database/schema";
import { escapeMarkdownV2 } from "../../../utils/formatText";
import { Context } from "telegraf";
import { User } from "../../../database/schema";

export const walletComposer = new Composer<MyContext>();

// View Wallet

const vewWallet = async (ctx: Context) => {
  const wallets = await Wallet.find({
    telegramId: ctx.from?.id,
  });

  if (!wallets.length) {
    return ctx.reply("No wallet found");
  }

  wallets.map((item) =>
    ctx.replyWithMarkdownV2(
      escapeMarkdownV2(`
  *💳 Wallet Details*

*Wallet Name:*  
${item.walletName}

*Address:*  
${item.publicKey}

*Network:*  
${item.chain}

*Balance:*  
${item.balance} SOL

*Created On:*  
${item.timeStamp?.toLocaleDateString()}

*Generated By Bot:*  
${item.botGenerated ? "Yes" : "No"}

*Status:*
✅ Active


`),
      {
        reply_markup: {
          inline_keyboard: [
            [
              {
                text: "💵 Fund Wallet",
                callback_data: "fund_wallet",
              },
            ],
            [{ text: " ❌ Remove Wallet", callback_data: "remove_wallet" }],
            item.botGenerated
              ? [{ text: " 📩 Export Wallet", callback_data: "export_wallet" }]
              : [],
          ],
        },
      }
    )
  );
  return;
};

// Manage Wallets ///////////////////////////////////////////////////////

const noWalletYet = escapeMarkdownV2(`
    **💼 Your Linked Wallets**

_No wallets have been added yet._

➡️ Tap **"➕ Add Wallet"** to link your first wallet or **"🔃 Generate Wallet"** to create a new wallet.

`);

const manageWallet = async (ctx: Context) => {
  // Check if user is linked in db
  const user = await User.findOne({ telegramId: ctx.from?.id });

  // No User found
  if (!user) {
    return ctx.reply("User not Found, please run the /start command", {
      reply_parameters: {
        message_id: ctx?.message?.message_id ?? 0,
      },
    });
  }

  const wallets = await Wallet.find({
    userId: user._id,
  });

  // No wallet Found
  if (!wallets.length) {
    return ctx.replyWithMarkdownV2(noWalletYet, {
      reply_markup: {
        inline_keyboard: [
          [{ text: "➕ Add Wallet", callback_data: "add_wallet" }],
          [{ text: "🔃 Generate Wallet", callback_data: "generate_wallet" }],
        ],
      },
      reply_parameters: {
        message_id: ctx?.message?.message_id ?? 0,
      },
    });
  }

  const walletList = escapeMarkdownV2(`
*💼 Your Linked Wallets*

${wallets.map((item, index) =>
  `${index + 1}. ${item.walletName}\n`.replaceAll(",", "")
)}

_You can add up to 5 wallets._

Select an action:

`);

  return ctx.replyWithMarkdownV2(walletList, {
    reply_markup: {
      inline_keyboard: [
        [{ text: "➕ Add Wallet", callback_data: "add_wallet" }],
        [{ text: "🔃 Generate Wallet", callback_data: "generate_wallet" }],
        [{ text: "✖️ Remove Wallet", callback_data: "find_remove_wallet" }],
        [{ text: "👁️ View Wallet", callback_data: "view_wallets" }],
      ],
    },
    reply_parameters: {
      message_id: ctx.message?.message_id ?? 0,
    },
  });
};

// Manage
walletComposer.command("managewallet", manageWallet);
walletComposer.hears("💼 Manage Wallets", manageWallet);
walletComposer.action("manage_wallet", async (ctx) => {
  await ctx.answerCbQuery("Loading...");
  await manageWallet(ctx);
});

// View
walletComposer.command("viewwallets", vewWallet);
walletComposer.action("view_wallets", async (ctx) => {
  await ctx.answerCbQuery("Loading...");
  await vewWallet(ctx);
});

// Add
walletComposer.action("add_wallet", async (ctx) => {
  await ctx.answerCbQuery("Loading...");
  await ctx.scene.enter("addWallet");
});
walletComposer.hears(
  "➕ Add Wallets",
  async (ctx) => await ctx.scene.enter("addWallet")
);

// Generate
walletComposer.action(
  "generate_wallet",
  async (ctx) => await ctx.scene.enter("walletScene")
);

walletComposer.hears(
  "🔃 Generate Wallet",
  async (ctx) => await ctx.scene.enter("walletScene")
);

// Remove
walletComposer.action("remove_wallet", async (ctx) => {
  await ctx.answerCbQuery("Loading...");
  await ctx.scene.enter("removeWallet");
});

walletComposer.action("find_remove_wallet", async (ctx) => {
  await ctx.answerCbQuery("Loading...");
  await ctx.scene.enter("removeWallet");
});

// Fund
walletComposer.action("fund_wallet", async (ctx) =>
  ctx.scene.enter("fundWallet")
);

// Export
walletComposer.action("export_wallet", async (ctx) => {
  const wallet = await Wallet.findOne({
    telegramId: ctx.from?.id,
  });
  ctx.replyWithMarkdownV2(
    escapeMarkdownV2(
      `
🔑 Your Private Key:
${wallet?.privateKey}

⚠️ WARNING:
Never share this private key with anyone!  
Anyone who has it can take full control of your wallet and all its funds.  
Keep it safe and secure. 🛡️
    `
    )
  );
});
